
/* Drop Tables */

DROP TABLE FILE_CHECK_RESULT;




/* Create Tables */

CREATE TABLE FILE_CHECK_RESULT
(
	FILE_HASH VARCHAR(64) NOT NULL,
	FILE_SEQ INTEGER NOT NULL,
	INPUT_DIR_PATH TEXT NOT NULL,
	INPUT_FILE_NAME TEXT NOT NULL,
	OUTPUT_DIR_PATH TEXT NOT NULL,
	OUTPUT_FILE_NAME TEXT NOT NULL,
	REGISTER_DATETIME TIMESTAMP NOT NULL,
	REGISTER_USER_ID TEXT NOT NULL,
	UPDATED_DATETIME TIMESTAMP NOT NULL,
	UPDATED_USER_ID TEXT NOT NULL,
	VERSION INTEGER NOT NULL,
	PRIMARY KEY (FILE_HASH, FILE_SEQ)
);



